fobj = open("sample.txt", 'w')
fobj.write('string')
fobj.write('list ')
fobj.write('tuple')
fobj.write('dictionary')
print("This is the last line.", file=fobj)
fobj.close()
fobj = open('sample.txt')
s = fobj.read()
print(s)
